Add missing #include <crypt.h>
dcapPasswd.c:35:34: error: implicit declaration of function 'crypt' [-Werror=implicit-function-declaration]
   35 |       strncpy(savepasswd, (char*)crypt(newpasswd, user), 100);
      |                                  ^~~~~